#hadd pfClusters_noPU_training.root pfClusters_noPU_0p1TO10_training.root pfClusters_noPU_10TO300_training.root
#hadd pfClusters_noPU_testing.root pfClusters_noPU_0p1TO10_testing.root pfClusters_noPU_10TO300_testing.root
hadd pfClusters_PU_training.root pfClusters_PU_0p01To5_training.root pfClusters_PU_5To300_training.root
hadd pfClusters_PU_testing.root pfClusters_PU_0p01To5_testing.root pfClusters_PU_5To300_testing.root 
#hadd pfClusters_noPU_PU_training.root pfClusters_noPU_training.root pfClusters_PU_training.root
#hadd pfClusters_noPU_PU_testing.root pfClusters_noPU_testing.root pfClusters_PU_testing.root