#!/bin/bash


#./applyRegression.exe -t testall_testing.root -o testall_application.root -c ../python/training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster -p /afs/cern.ch/work/s/shilpi/work/2015/Egamma_work_PFcluster/PFClusterRegressionsDB/V2/Config_May8_pfcluster

#./applyRegression.exe -t pfClusters_noPU_PU_testing.root -o pfClusters_noPU_PU_application.root -c ../python/training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster -p ../training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster

#./applyRegression.exe -t /eos/cms/store/group/phys_egamma/PFClusterCalibration/MC18_V2/FlatTrees/DoublePhotonNoMaterial_FlatPt-0p01To5/crab_PFclusterPU0p01To5/180128_085340/0000/tree_1.root -o pfClusters_PU_application.root -c ../python/training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster -p ../training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster


#./applyRegression.exe -t pfClusters_PU_testing.root -o pfClusters_PU_application.root -c ../python/training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster -p ../training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster

./applyRegression.exe -t /eos/cms/store/group/phys_egamma/PFClusteRegressionTrees/afterDebug_16june/pfClusters_PU_testing.root -o pfClusters_PU_application_OLD.root -c ../python/training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster -p ../training_all_weights_NOPU_nbinsFlag_nhits123AsInput_FULLnoPUstats_NOPTETA_AFTERDEBUG16june/Config_May8_pfcluster