void plot_checked_CMSSW_mycode()
{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Sep 10 18:09:21 2019) by ROOT version 6.12/07
   TCanvas *c1 = new TCanvas("c1", "c1",10,32,700,502);
   c1->Range(-325,-1.575,2925,14.175);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *htemp__1 = new TH1F("htemp__1","cluscorrE",100,0,2600);
   htemp__1->SetBinContent(1,2);
   htemp__1->SetBinContent(2,9);
   htemp__1->SetBinContent(3,4);
   htemp__1->SetBinContent(4,6);
   htemp__1->SetBinContent(5,5);
   htemp__1->SetBinContent(6,9);
   htemp__1->SetBinContent(7,12);
   htemp__1->SetBinContent(8,5);
   htemp__1->SetBinContent(9,8);
   htemp__1->SetBinContent(10,3);
   htemp__1->SetBinContent(11,7);
   htemp__1->SetBinContent(12,1);
   htemp__1->SetBinContent(13,6);
   htemp__1->SetBinContent(14,3);
   htemp__1->SetBinContent(15,8);
   htemp__1->SetBinContent(16,4);
   htemp__1->SetBinContent(17,2);
   htemp__1->SetBinContent(18,3);
   htemp__1->SetBinContent(19,1);
   htemp__1->SetBinContent(24,2);
   htemp__1->SetBinContent(25,1);
   htemp__1->SetBinContent(27,1);
   htemp__1->SetBinContent(29,1);
   htemp__1->SetBinContent(36,2);
   htemp__1->SetBinContent(41,1);
   htemp__1->SetBinContent(76,1);
   htemp__1->SetBinContent(83,1);
   htemp__1->SetBinContent(92,1);
   htemp__1->SetEntries(109);
   htemp__1->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(2);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("htemp");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 109    ");
   ptstats_LaTex = ptstats->AddText("Mean  =    310");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  367.1");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   htemp__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(htemp__1);
   htemp__1->SetLineColor(2);
   htemp__1->SetLineWidth(2);
   htemp__1->GetXaxis()->SetTitle("cluscorrE");
   htemp__1->GetXaxis()->SetRange(1,100);
   htemp__1->GetXaxis()->SetLabelFont(42);
   htemp__1->GetXaxis()->SetLabelSize(0.035);
   htemp__1->GetXaxis()->SetTitleSize(0.035);
   htemp__1->GetXaxis()->SetTitleFont(42);
   htemp__1->GetYaxis()->SetLabelFont(42);
   htemp__1->GetYaxis()->SetLabelSize(0.035);
   htemp__1->GetYaxis()->SetTitleSize(0.035);
   htemp__1->GetYaxis()->SetTitleOffset(0);
   htemp__1->GetYaxis()->SetTitleFont(42);
   htemp__1->GetZaxis()->SetLabelFont(42);
   htemp__1->GetZaxis()->SetLabelSize(0.035);
   htemp__1->GetZaxis()->SetTitleSize(0.035);
   htemp__1->GetZaxis()->SetTitleFont(42);
   htemp__1->Draw("");
   
   TPaveText *pt = new TPaveText(0.4112034,0.94,0.5887966,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("cluscorrE");
   pt->Draw();
   
   TH1F *htemp__2 = new TH1F("htemp__2","e91X",100,0,2600);
   htemp__2->SetBinContent(1,2);
   htemp__2->SetBinContent(2,9);
   htemp__2->SetBinContent(3,4);
   htemp__2->SetBinContent(4,6);
   htemp__2->SetBinContent(5,5);
   htemp__2->SetBinContent(6,9);
   htemp__2->SetBinContent(7,12);
   htemp__2->SetBinContent(8,5);
   htemp__2->SetBinContent(9,8);
   htemp__2->SetBinContent(10,3);
   htemp__2->SetBinContent(11,7);
   htemp__2->SetBinContent(12,1);
   htemp__2->SetBinContent(13,6);
   htemp__2->SetBinContent(14,3);
   htemp__2->SetBinContent(15,8);
   htemp__2->SetBinContent(16,4);
   htemp__2->SetBinContent(17,2);
   htemp__2->SetBinContent(18,3);
   htemp__2->SetBinContent(19,1);
   htemp__2->SetBinContent(24,2);
   htemp__2->SetBinContent(25,1);
   htemp__2->SetBinContent(27,1);
   htemp__2->SetBinContent(29,1);
   htemp__2->SetBinContent(36,2);
   htemp__2->SetBinContent(41,1);
   htemp__2->SetBinContent(76,1);
   htemp__2->SetBinContent(83,1);
   htemp__2->SetBinContent(92,1);
   htemp__2->SetEntries(109);
   htemp__2->SetDirectory(0);
   
   ptstats = new TPaveStats(0.782235,0.5822785,0.982808,0.742616,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(4);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("htemp");
   ptstats_LaTex->SetTextSize(0.03687764);
   ptstats_LaTex = ptstats->AddText("Entries = 109    ");
   ptstats_LaTex = ptstats->AddText("Mean  =    310");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  367.1");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   htemp__2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(htemp__2);
   htemp__2->SetLineColor(4);
   htemp__2->GetXaxis()->SetTitle("e91X");
   htemp__2->GetXaxis()->SetLabelFont(42);
   htemp__2->GetXaxis()->SetLabelSize(0.035);
   htemp__2->GetXaxis()->SetTitleSize(0.035);
   htemp__2->GetXaxis()->SetTitleFont(42);
   htemp__2->GetYaxis()->SetLabelFont(42);
   htemp__2->GetYaxis()->SetLabelSize(0.035);
   htemp__2->GetYaxis()->SetTitleSize(0.035);
   htemp__2->GetYaxis()->SetTitleOffset(0);
   htemp__2->GetYaxis()->SetTitleFont(42);
   htemp__2->GetZaxis()->SetLabelFont(42);
   htemp__2->GetZaxis()->SetLabelSize(0.035);
   htemp__2->GetZaxis()->SetTitleSize(0.035);
   htemp__2->GetZaxis()->SetTitleFont(42);
   htemp__2->Draw("sames");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
